theme: jekyll-theme-minimal
title: Quelques Digressions Sous GPL
description: Cloud security, risk management and web services engineering. Author of [Securing DevOps](https://securing-devops.com).
logo: img/id2015.JPG

github:
  is_project_page: false
  is_user_page: false
show_downloads: false