theme: jekyll-theme-minimal
title: Quelques Digressions Sous GPL
description: Cloud security, risk management and web services engineering. Author of <a href="https://securing-devops.com>Securing DevOps</a>.
logo: img/id2015.JPG
github.is_project_page: false
github.is_user_page: false
show_downloads: false