theme: jekyll-theme-minimal
title: Quelques Digressions Sous GPL
description: Julien Vehent on cloud security, risk management and web services engineering.
#logo: img/DSC00584%20(1).JPG

github:
  is_project_page: false
  is_user_page: false
show_downloads: false
