theme: jekyll-theme-minimal
title: Quelques Digressions Sous GPL
description: Cloud security, risk management and services engineering. Author of Securing DevOps (securing-devops.com).
logo: img/id2015.JPG
url: jvehent.github.io
baseurl: /jvehent.org